version: 0.0.0.{build}
os: Visual Studio 2015
configuration:
#- Coverity
- Release
- Debug
platform: x64
environment:
  CoverityToken:
    secure: OfUyk9tr3AlhoCMaSc9VGWvjDUXS1UDIkmtXN8gAuFA=
  CoverityMail:
    secure: fsImKF76tplc9AeyOQTMYA==    
before_build:
- ps: |
    $path = $Env:APPVEYOR_BUILD_FOLDER
    Write-Host "CONFIGURATION ="$Env:CONFIGURATION
    Write-Host "APPVEYOR_BUILD_FOLDER ="$path

    Write-Host "Updating submodules.."
    git submodule update

    Write-Host "Bootstrapping boost.."
    Set-Location "$Env:APPVEYOR_BUILD_FOLDER\src\external\boost"
    .\bootstrap.bat

    $buildCmd = "./b2"

    Write-Host "Generating boost headers"
    $buildArgs = @("headers" "-d0")
    & $buildCmd $buildArgs
    
    if ($Env:CONFIGURATION -eq "Debug") {
        Write-Host "Building boost.."
        
        $buildArgs = @(
        "-d0",
        "address-model=64",
        "toolset=msvc-14.0",
        "windows-api=desktop",
        "variant=debug",
        "link=static",
        "threading=multi",
        "runtime-link=shared",
        "--with-log")
        & $buildCmd $buildArgs
    }
build_script:
- ps: |
    Write-Host "Build step starting.."
    $buildCmd = "C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe"
    $buildArgs = @(
          "$Env:APPVEYOR_BUILD_FOLDER\build\Takoyaki.sln",
          "/l:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll",
          "/p:Configuration=$Env:CONFIGURATION",
          "/p:Platform=$env:PLATFORM",
          "/verbosity:minimal")

    & $buildCmd $buildArgs
test: off
notifications:
- provider: Slack
  auth_token:
    secure: NL05oTnkUQ8es7KG6L70RSOPTd6rV9/bq00OrCiEpfuIZ4NOV008mHhbG7J+YZeXBy1VzEzNgZXFNimtGhALXQ==
  channel: bots
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
