version: 0.0.0.{build}
os: Visual Studio 2015
configuration:
- Release
- Coverity
- Debug
platform: x64
environment:
  BOOST_ROOT: $(APPVEYOR_BUILD_FOLDER)\boost_1_59_0
  CoverityToken:
    secure: OfUyk9tr3AlhoCMaSc9VGWvjDUXS1UDIkmtXN8gAuFA=
  CoverityMail:
    secure: fsImKF76tplc9AeyOQTMYA==    
before_build:
- ps: |
    Write-Host "Pre-build step starting.."
    Add-Type -assembly "System.IO.Compression.Filesystem"
    $path = $Env:APPVEYOR_BUILD_FOLDER
    $type = $Env:CONFIGURATION
    Write-Host "CONFIGURATION="$type
    Write-Host "APPVEYOR_BUILD_FOLDER="$path
    Write-Host "Downloading boost.."
    (new-object net.webclient).DownloadFile("http://bit.ly/1JPHkL3", "$path\boost_1_59_0.zip")
    Write-Host "Extracting archive.."
    [io.compression.zipfile]::ExtractToDirectory("$path\boost_1_59_0.zip", $path)
    Set-Location "$path\boost_1_59_0"
    Write-Host "Building boost.."
    .\bootstrap.bat
    if ($type -eq "Coverity") {
        $buildCmd = "./b2"
        $buildArgs = @(
            "address-model=64",
            "toolset=msvc-14.0",
            "windows-api=desktop",
            "variant=debug",
            "link=static",
            "threading=multi",
            "runtime-link=shared",
            "--with-log")
        cov-build.exe --dir cov-int --encoding=UTF-8 $buildCmd $buildArgs
    } elseif ($type -eq "Debug") {
        .\b2 address-model=64 toolset=msvc-14.0 windows-api=desktop variant=debug link=static threading=multi runtime-link=shared --with-log
    } else {
        .\b2 address-model=64 toolset=msvc-14.0 windows-api=desktop variant=release link=static threading=multi runtime-link=shared --with-thread --with-date_time
    }
build_script:
- ps: |
    Write-Host "Build step starting.."
    $buildCmd = "C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe"
    $buildArgs = @(
          "$Env:APPVEYOR_BUILD_FOLDER\build\Takoyaki.sln",
          "/l:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll",
          "/p:Configuration=Release",
          "/p:Platform=$env:PLATFORM",
          "/verbosity:minimal")
    if ($env:CONFIGURATION -eq "Coverity") {
        Write-Host "Building project with Coverity..."
        cov-build.exe --dir cov-int --encoding=UTF-8 $buildCmd $buildArgs
        Write-Host "Compressing Coverity report..."
        $zipEncoderDef = @'
            namespace AnalyzeCode {
                public class PortableFileNameEncoder: System.Text.UTF8Encoding {
                    public PortableFileNameEncoder() {}
                    public override byte[] GetBytes(string entry) {
                        return base.GetBytes(entry.Replace("\\", "/"));
                    }
                }
            }
    '@
        Add-Type -TypeDefinition $zipEncoderDef
        [IO.Compression.ZipFile]::CreateFromDirectory(
            "$env:APPVEYOR_BUILD_FOLDER\cov-int",
            "$env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_PROJECT_NAME.zip",
            [IO.Compression.CompressionLevel]::Optimal,
            $true,  # include root directory
            (New-Object AnalyzeCode.PortableFileNameEncoder))
            
        
        Write-Host "Uploading report to Coverity..."
        Add-Type -AssemblyName "System.Net.Http"
        $client = New-Object Net.Http.HttpClient
        $client.Timeout = [TimeSpan]::FromMinutes(30)
        $form = New-Object Net.Http.MultipartFormDataContent
        # Fill token field.
        [Net.Http.HttpContent]$formField =
          New-Object Net.Http.StringContent($env:CoverityToken)
        $form.Add($formField, "token")
        # Fill email field.
        $formField =
          New-Object Net.Http.StringContent($env:CoverityMail)
        $form.Add($formField, "email")            
                
        # Fill file field.
        $fs = New-Object IO.FileStream(
          "$env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_PROJECT_NAME.zip",
          [IO.FileMode]::Open,
          [IO.FileAccess]::Read)
        $formField = New-Object Net.Http.StreamContent($fs)
        $form.Add($formField, "file", "$env:APPVEYOR_PROJECT_NAME.zip")
        # Fill version field.
        $version = "$env:VersionMajor.$env:VersionMinor.$env:VersionPatch" +
          "-$env:VersionStage+$env:VersionBuild"
        $formField = New-Object Net.Http.StringContent($version)
        $form.Add($formField, "version")
        # Fill description field.
        $formField =
          New-Object Net.Http.StringContent("AppVeyor build.")
        $form.Add($formField, "description")
        # Submit form.
        $url = "https://scan.coverity.com/builds?project=$env:APPVEYOR_REPO_NAME"
        $task = $client.PostAsync($url, $form)
        try {
          $task.Wait()  # throws AggregateException on time-out
        } catch [AggregateException] {
          throw $_.Exception.InnerException
        }
        $task.Result
        $fs.Close()        
    } else {
        & $buildCmd $buildArgs
    }
test: off
notifications:
- provider: Slack
  auth_token:
    secure: NL05oTnkUQ8es7KG6L70RSOPTd6rV9/bq00OrCiEpfuIZ4NOV008mHhbG7J+YZeXBy1VzEzNgZXFNimtGhALXQ==
  channel: bots
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
